### ISSUE TITLE
Add recommended citation

### ISSUE THREAD

**Issue by grgmiller** [singularity-energy/open-grid-emissions#191]
Add a citation file to the top level directory. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
```
cff-version: 1.2.0
message: "If you use this repository, please cite it as below."
authors:
- family-names: "Miller"
  given-names: "Gregory"
  orcid: "https://orcid.org/0000-0003-3750-9292"
- family-names: "Pease"
  given-names: "Gailin"
title: "Open Grid Emissions Initiative"
version: 1.0.0
doi: [need to add from zenodo]
date-released: 2022-08-30
url: "https://github.com/singularity-energy/open-grid-emissions"
```
